### ISSUE TITLE
Having two mice connected allows me to select which one to configure, but the serials displayed don't match what are on the mice

### ISSUE THREAD

**Issue by leviport** [pop-os/mouse-configurator#16]
![2022-06-06_17-07](https://user-images.githubusercontent.com/13512097/172264292-8c80c720-3b81-4f00-ad00-2857a64a763d.png)
![PXL_20220606_231107374](https://user-images.githubusercontent.com/13512097/172264302-bc1a6f7d-4c59-4df8-a3bc-1dd0671745fc.jpg)

Since very few people are likely to use more than one of these mice on a single machine, this is probably a fairly low priority bug.

I also noticed that in the "about" dialog, the serial also doesn't match what is printed on the mouse.

**Comment by ids1024** [comment]
Yeah, I've noticed this. Though this is the ID that's given by the firmware. As far as I'm aware there's (unfortunately) no way to get the same serial printed on the device.

It seems this is the same as what's reported by the Windows software, though it calls it a "Unique ID", rather than a serial. We could label it similarly if that is likely to be less confusing:

![Screenshot 2022-06-06 162910](https://user-images.githubusercontent.com/2263150/172265705-4ce906c2-d7b9-406e-a0fd-677a912013f0.png)

The device selection UI could probably be better than just a centered listbox, but it's not expected to be seen much as long as it only supports this device.

**Comment by leviport** [comment]
Yeah I think "Unique ID" would probably be less confusing

**Comment by ids1024** [comment]
Renamed to "Unique ID" here and in the info screen. I think that's the best thing we can do about this.

**Comment by leviport** [comment]
Agreed. Fix looks good to me!
